### ISSUE TITLE
Customize templates for the non-standard steps

### ISSUE THREAD

**Issue by fureigh** [18F/ffd-info-exchange#122]
Now that #64 is complete, we have more control over the individual steps. Breaking them out and addressing them here.

* [x] Step 5
* [ ] ~Step 6~ (handle this when adding data review: #124)
* [x] Step 7 ("sign and pay")
* [x] Additional services (#130 has the remainder)
* [x] Name change application
* [x] Global Entry/TSA PreCheck application
* [ ] ~Passport application~ (not yet implemented, so will handle in one fell swoop in #104)
